openapi: 3.0.3
info:
  title: API binar rental cars
  description: API to manage binar rental cars application
  version: 1.0.0
servers:
  - url : http://localhost:8000/api/v1
    description: Local server
paths:
  /cars:
    get:
      summary: Get List All Cars
      tags: 
        - Cars
      responses:
        '200':
          description: A list of cars
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Cars'
    post:
      summary: Create Data Cars
      tags: 
        - Cars
      requestBody:
        description: Car to create
        required: True
        content:
          application/json:
            schema: 
              type: object
              items:
                $ref: '#/components/schemas/InputCars'
      responses:
        '201':
          description: Cars created successfuly
          content:
            application/json:
              schema:
                type: object
                items:
                  $ref: '#/components/schemas/Cars'
components:
  schemas:
    Cars:
      type: object
      properties:
        id : 
          type: integer
          example: 1
        name: 
          type: string
          example: "Fortuner"
        availability: 
          type: boolean
          example: True
        price: 
          type: integer
          example: 400000
        category: 
          type: string
          example: "Dengan Driver"
        image: 
          type: string
          example: "fortuner1.jpg"
        start_date: 
          type: string
          example: '2024-05-28'
        end_date: 
          type: string
          example: '2024-05-28'
    InputCars:
      type: object
      properties:
        name: 
          type: string
          example: "Fortuner"
        availability: 
          type: boolean
          example: True
        price: 
          type: integer
          example: 400000
        category: 
          type: string
          example: "Dengan Driver"
        image: 
          type: string
          example: "fortuner1.jpg"
        start_date: 
          type: string
          example: '2024-05-28'
        end_date: 
          type: string
          example: '2024-05-28'